version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./master.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - ./master/ansible:/root/playbooks
    command: tail -f /dev/null

  web:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    ports:
      - 8080:80

  db:
    build:
      context: .
      dockerfile: ./server.Dockerfile
