version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./master.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - /b/Ansible/playbooks:/root/playbooks
      - /b/Ansible/config:/etc/ansible
    command: tail -f /dev/null

  web:
    build:
      context: .
      dockerfile: ./server.Dockerfile

  db:
    build:
      context: .
      dockerfile: ./server.Dockerfile

  lb:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    ports:
    - 8080:80
